---
  - hosts: all
    
    vars_files:
     - vars.yml
    
    pre_tasks:
      - name: Update apt cache
        apt: update_cache=yes cache_valid_time=3600
    
    handlers:
      - name: restart solr
        service: name=solr state=restarted
    tasks:
      - name: Install java
        apt: name=openjdk-8-jdk state=present
      
      - name: Download solr
        get_url:
           url: "https://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz"
           dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
           checksum: "{{ solr_checksum }}"
      - name: Expand solr
        unarchive:
           src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
           dest: "{{ download_dir }}"
           copy: false
           creates: "{{ donwload_dir }}/solr-{{ solr_version }}/README.txt"
      - name: Run solr instalation script
        shell: > 
           {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr_service.sh
           {{ download_dir }}/solr-{{ solr_version }}.tgz
           -i /opt
           -d /var/solr
           -u solr
           -s solr
           -p 8983
           creates={{ solr_dir }}/bin/solr
      - name: Ensure solr autoload
        service: name=solar state=started enabled=yes

    