VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
# general VM configuration
    config.vm.box = "ubuntu/xenial64"
    config.vm.box_version = "20201102.0.0"
    config.ssh.insert_key = false
    config.vm.synced_folder  ".", "/vagrant", disabled: true
    config.vm.provider :virtualbox do |v|
        v.memory = 512
        v.linked_clone = true
      end
    
    config.vm.define "xenial" do |xenial|
        xenial.vm.hostname = "lamp.my.srv"
        xenial.vm.network :public_network, ip: "192.168.178.123"
        end
    end