---
- hosts: multi
  
  vars_files:
    - vars.yml/api_key.yml
  
  tasks:
     - name: Connect to server API
       command: connect_to_service
       environment: 
          SERVICE_API_KEY: "{{ myapp_service_api_key }}"
