ubuntu ansible_host=192.168.178.188
centos ansible_host=192.168.178.199
suse   ansible_host=192.168.178.200

[os1]
ubuntu

[os2]
centos



[my:children]
os1
os2



[all:vars]
ansible_ssh_private_key=./insecure_private_key
ansible_ssh_user=vagrant
ansible_host_key_ckecking=false



