---
- name: Upgrade system
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    - ubuntu_version: "20.04"
    - centos_version: "7.9"
  tasks:
   - name: Updating system
     package:
       name: "*"
       state: latest
     when: (ansible_distribution == "CentOS" and ansible_distribution_version != centos_version) or
           (ansible_distribution == "Ubuntu" and ansible_distribution_version == ubuntu_version)
