VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
# general VM configuration
    config.vm.box = "ubuntu/bionic64"
    config.vm.box_version = "20220713.0.0"
    config.ssh.insert_key = false
    config.vm.synced_folder  ".", "/vagrant", disabled: true
    config.vm.provider :virtualbox do |v|
        v.memory = 512
        v.linked_clone = true
      end
    
    config.vm.define "lamp" do |lamp|
        lamp.vm.hostname = "lamp.my.srv"
        lamp.vm.network :public_network, ip: "192.168.178.121"
        end
    config.vm.define "lamp1" do |lamp|
        lamp.vm.hostname = "lamp1.my.srv"
        lamp.vm.network :public_network, ip: "192.168.178.122"
        end
end