---
 - hosts: ubuntu
   become: true
   vars_files:
     - "vars.yml"
     
   handlers:
    - name: Restart httpd
      service: 
        name: apache2
        state: restarted

   tasks:
     - name: Install apache ubuntu
       apt:   
         name: "{{ soft }}"
         update_cache: yes
       notify: Restart httpd 