VAGRANTFILE_API_VERSION = "2"
Vagrant.configure("2") do |config|
    config.vm.box = "generic/opensuse42"
    config.ssh.insert_key = false
    config.vm.synced_folder  ".", "/vagrant", disabled: true
    config.vm.provider :virtualbox do |v|
        v.memory = 512
        v.linked_clone = true
    end    
    config.vm.define "suse" do |suse|
        suse.vm.hostname = "suse"
        suse.vm.box = "generic/opensuse42"
        suse.vm.network :public_network, ip: "192.168.178.200"
    end
end