VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
# general VM configuration
    config.vm.box = "ubuntu/focal64"
    config.vm.box_version = "20220715.0.0"
    config.ssh.insert_key = false
    config.vm.synced_folder  ".", "/vagrant", disabled: true
    config.vm.provider :virtualbox do |v|
        v.memory = 512
        v.linked_clone = true
      end
    
    config.vm.define "srv" do |srv|
        srv.vm.hostname = "srv"
        srv.vm.network :public_network, ip: "192.168.178.124"
    config.vm.network "forwarded_port",
        id: 'http', guest: 80, host: 8080, host_ip: "127.0.0.1"
    config.vm.network "forwarded_port",
        id: 'https', guest: 443, host: 8443, host_ip: "127.0.0.1"
        # disable updating guest additions
        #if Vagrant.has_plugin?("vagrant-vbguest")
        #config.vbguest.auto_update = false
        end   
    config.vm.provider "srv" do |virtualbox| 
        virtualbox.name = "ch02"
     end
    config.vm.define "srv_db" do |srv|
      srv.vm.hostname = "srv.db"
      srv.vm.network :public_network, ip: "192.168.178.125"
      srv.vm.network :public_network, ip: "192.168.60.15"   
      config.vm.network "forwarded_port",
      id: 'http', guest: 80, host: 7080, host_ip: "127.0.0.1"
      config.vm.network "forwarded_port",
      id: 'https', guest: 443, host: 7443, host_ip: "127.0.0.1"
      # disable updating guest additions
      #if Vagrant.has_plugin?("vagrant-vbguest")
    #config.vbguest.auto_update = false
     # end
      config.vm.provider "srv_db" do |virtualbox| 
      virtualbox.name = "ch03"
      end    
    end
  end